package usealist;

import java.lang.reflect.Method;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public class SImple {
//  public static int doStuff() { return 0; }
//  public static long doStuff() { return 0; }
//
//  public static void takeAList(List<String> ls) {}
//  public static void takeAList(List<LocalDate> ls) {}

  public static void breakList(List l) {
    l.add(0, LocalDate.now());
  }

  public static void main(String[] args) {
    var l = List.<String>of("Fred");

//    List<String> names = new ArrayList();
//    List<String> names = new ArrayList<String>(List.of(LocalDate.now(), "Albert"));
    List<String> names = new ArrayList<>(List.of(/*LocalDate.now(), */"Albert"));
//    var names = new ArrayList<>(List.of(/*LocalDate.now(), */"Albert"));
    names = Collections.checkedList(names, String.class);
    names.add("Fred");
    names.add("Jim");
//    names.add(LocalDate.now());
//    breakList(names);
    System.out.println(names);
//    Object object = names.get(0);
//    String object = (String)names.get(0);
    String object = names.get(0); // cast is generated by the compiler
    System.out.println("item zero is " + object);

//    Object obj = new ArrayList<String>(List.of("Fred", "Jim"));
    Collection<String> obj = new ArrayList<String>(List.of("Fred", "Jim"));
//    Collection<Integer> obj = null;
    if (obj instanceof List<String> aList) {
//      List<String> aList = (List<String>)obj;
      System.out.println("yes, it's a list");
      String first = aList.get(0);
      System.out.println("first element in list is " + first);
    }

//    Class cls = "".getClass();
//    Method[] methods = cls.getDeclaredMethods();
//    for (Method m : methods) {
//      System.out.println("> " + m);
//    }
//
//    Class cls2 = "Banana".getClass();
//    System.out.println(cls == cls2);
  }
}
